package no.uib.inf101.tools;

import javax.swing.*;
import java.awt.*;

// Generated by ChatGPT 22.04.2024 20:29:00

public class FontExample extends JFrame {
    public FontExample() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Font Example");
        setSize(600, 400);

        JPanel panel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;

                int y = 50;

                // Sans-Serif Fonts
                drawStringWithFont(g2d, "Arial", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Verdana", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Calibri", Font.PLAIN, y);

                y += 100;

                // Serif Fonts
                drawStringWithFont(g2d, "Times New Roman", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Georgia", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Palatino", Font.PLAIN, y);

                y += 100;

                // Monospaced Fonts
                drawStringWithFont(g2d, "Courier New", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Consolas", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Monaco", Font.PLAIN, y);

                y += 100;

                // Cursive Fonts
                drawStringWithFont(g2d, "Comic Sans MS", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Brush Script", Font.PLAIN, y);

                y += 100;

                // Fantasy Fonts
                drawStringWithFont(g2d, "Impact", Font.PLAIN, y);
                y += 50;
                drawStringWithFont(g2d, "Chiller", Font.PLAIN, y);
            }

            private void drawStringWithFont(Graphics2D g2d, String fontName, int fontStyle, int y) {
                Font font = new Font(fontName, fontStyle, 20);
                g2d.setFont(font);
                g2d.drawString(fontName, 50, y);
            }
        };

        add(panel);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(FontExample::new);
    }
}
